### ISSUE TITLE
latest alpha build segfaults

### ISSUE THREAD

**Issue by centminmod** [h2o/h2o#251] opened 2015-03-26 03:02 UTC
I updated h2o to latest master branch's build today and seems h2o is segfaulting now ? how to diagnose ?

    [OCSP Stapling] successfully updated the response for certificate file:/usr/local/h2o/centminmod.com-unified.crt
    [INFO] raised RLIMIT_NOFILE to 65536
    h2o server (pid:25875) is ready to serve requests
    fetch-ocsp-response (using OpenSSL 1.0.1e-fips 11 Feb 2013)
    sending OCSP request to http://ocsp.comodoca.com
    /usr/local/h2o/centminmod.com-unified.crt: good
            This Update: Mar 24 16:39:21 2015 GMT
            Next Update: Mar 28 16:39:21 2015 GMT
    verifying the response signature
    verify OK (used: -VAfile /tmp/J7e7YnVuHm/issuer.crt)
    
    [1]+  Segmentation fault      /usr/local/bin/h2o -c /usr/local/h2o/h2o.conf

h2o last 2 commits for version segfaulting

    git log -n2
    commit 39fe066f3a309b3a14723e305abcd4cd8fdad52b
    Author: Kazuho Oku <kazuhooku@gmail.com>
    Date:   Tue Mar 24 17:28:49 2015 +0900
    
        doc-comment the probable failure of t/40max-connections.t
    
    commit ac0a855422a0b02b93c10cbf9de93fb96f67a215
    Merge: 801188b 264a77e
    Author: Kazuho Oku <kazuhooku@gmail.com>
    Date:   Tue Mar 24 15:20:04 2015 +0900
    
        Merge pull request #248 from h2o/kazuho/bundle-libyaml
        
        bundles libyaml

**Comment by kazuho** [comment] 2015-03-26 03:16
Would you mind clearing the build cache (by removing CMakeCache.txt and CMakeFiles directory) and rerun cmake and make?

From commit ac0a855 (merge of #248) the application source files are expected to include yaml.h under `deps/yaml/include`.  The problem is most likely due to some object files not being rebuilt, or a problem in the header search paths.

**Comment by centminmod** [comment] 2015-03-26 12:54
still segfaults with latest git pull for master

    /usr/local/bin/h2o -c /usr/local/h2o/h2o.conf
    fetch-ocsp-response (using OpenSSL 1.0.1e-fips 11 Feb 2013)
    sending OCSP request to http://ocsp.comodoca.com
    /usr/local/h2o/centminmod.com-unified.crt: good
            This Update: Mar 26 03:22:25 2015 GMT
            Next Update: Mar 30 03:22:25 2015 GMT
    verifying the response signature
    verify OK (used: -VAfile /tmp/Pmcl7AkK9Z/issuer.crt)
    [OCSP Stapling] successfully updated the response for certificate file:/usr/local/h2o/centminmod.com-unified.crt
    fetch-ocsp-response (using OpenSSL 1.0.1e-fips 11 Feb 2013)
    sending OCSP request to http://ocsp.comodoca.com
    /usr/local/h2o/centminmod.com-unified.crt: good
            This Update: Mar 26 03:22:25 2015 GMT
            Next Update: Mar 30 03:22:25 2015 GMT
    verifying the response signature
    verify OK (used: -VAfile /tmp/4Pfgw4PPj2/issuer.crt)
    [OCSP Stapling] successfully updated the response for certificate file:/usr/local/h2o/centminmod.com-unified.crt
    [INFO] raised RLIMIT_NOFILE to 65536
    h2o server (pid:18447) is ready to serve requests
    Segmentation fault
    fetch-ocsp-response (using OpenSSL 1.0.1e-fips 11 Feb 2013)
    sending OCSP request to http://ocsp.comodoca.com
    /usr/local/h2o/centminmod.com-unified.crt: good
            This Update: Mar 26 03:22:25 2015 GMT
            Next Update: Mar 30 03:22:25 2015 GMT
    verifying the response signature
    verify OK (used: -VAfile /tmp/MSTbN_JzeN/issuer.crt)

recompiling output

    rm -rf CMakeCache.txt
    rm -rf CMakeFiles

still reports openssl 1.0.1e despite being OpenSSL 1.0.2a-chacha build

    cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INCLUDE_PATH=${STATICLIBSSL}/include -DCMAKE_LIBRARY_PATH=${STATICLIBSSL}/lib .
    -- The C compiler identification is GNU 4.4.7
    -- The CXX compiler identification is GNU 4.4.7
    -- Check for working C compiler: /usr/bin/ccache
    -- Check for working C compiler: /usr/bin/ccache -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/ccache
    -- Check for working CXX compiler: /usr/bin/ccache -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Found PkgConfig: /usr/bin/pkg-config (found version "0.23") 
    -- Looking for include file pthread.h
    -- Looking for include file pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE  
    -- Found OpenSSL: /opt/h2o_openssl/lib/libssl.a;/opt/h2o_openssl/lib/libcrypto.a (found version "1.0.1e") 
    -- checking for module 'libuv>=1.0.0'
    --   package 'libuv>=1.0.0' not found
    -- Could NOT find LIBUV (missing:  LIBUV_LIBRARIES LIBUV_INCLUDE_DIR) 
    -- checking for module 'libwslay'
    --   package 'libwslay' not found
    -- Could NOT find WSLAY (missing:  WSLAY_LIBRARIES WSLAY_INCLUDE_DIR) 
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /svr-setup/h2o_git

make
    
    make
    Scanning dependencies of target bundled-ssl
    [  0%] Built target bundled-ssl
    Scanning dependencies of target h2o
    [  3%] Building C object CMakeFiles/h2o.dir/deps/picohttpparser/picohttpparser.c.o
    [  3%] Building C object CMakeFiles/h2o.dir/lib/common/hostinfo.c.o
    [  7%] Building C object CMakeFiles/h2o.dir/lib/common/http1client.c.o
    [  7%] Building C object CMakeFiles/h2o.dir/lib/common/memory.c.o
    [ 10%] Building C object CMakeFiles/h2o.dir/lib/common/multithread.c.o
    [ 10%] Building C object CMakeFiles/h2o.dir/lib/common/serverutil.c.o
    [ 14%] Building C object CMakeFiles/h2o.dir/lib/common/socket.c.o
    [ 14%] Building C object CMakeFiles/h2o.dir/lib/common/socketpool.c.o
    [ 17%] Building C object CMakeFiles/h2o.dir/lib/common/string.c.o
    [ 21%] Building C object CMakeFiles/h2o.dir/lib/common/time.c.o
    [ 21%] Building C object CMakeFiles/h2o.dir/lib/common/timeout.c.o
    [ 25%] Building C object CMakeFiles/h2o.dir/lib/common/url.c.o
    [ 25%] Building C object CMakeFiles/h2o.dir/lib/core/config.c.o
    [ 28%] Building C object CMakeFiles/h2o.dir/lib/core/configurator.c.o
    [ 28%] Building C object CMakeFiles/h2o.dir/lib/core/context.c.o
    [ 32%] Building C object CMakeFiles/h2o.dir/lib/core/headers.c.o
    [ 32%] Building C object CMakeFiles/h2o.dir/lib/core/proxy.c.o
    [ 35%] Building C object CMakeFiles/h2o.dir/lib/core/request.c.o
    [ 35%] Building C object CMakeFiles/h2o.dir/lib/core/token.c.o
    [ 39%] Building C object CMakeFiles/h2o.dir/lib/core/util.c.o
    [ 39%] Building C object CMakeFiles/h2o.dir/lib/handler/access_log.c.o
    [ 42%] Building C object CMakeFiles/h2o.dir/lib/handler/chunked.c.o
    [ 46%] Building C object CMakeFiles/h2o.dir/lib/handler/expires.c.o
    [ 46%] Building C object CMakeFiles/h2o.dir/lib/handler/file.c.o
    [ 50%] Building C object CMakeFiles/h2o.dir/lib/handler/headers.c.o
    [ 50%] Building C object CMakeFiles/h2o.dir/lib/handler/mimemap.c.o
    [ 53%] Building C object CMakeFiles/h2o.dir/lib/handler/proxy.c.o
    [ 53%] Building C object CMakeFiles/h2o.dir/lib/handler/redirect.c.o
    [ 57%] Building C object CMakeFiles/h2o.dir/lib/handler/reproxy.c.o
    [ 57%] Building C object CMakeFiles/h2o.dir/lib/handler/configurator/access_log.c.o
    [ 60%] Building C object CMakeFiles/h2o.dir/lib/handler/configurator/expires.c.o
    [ 60%] Building C object CMakeFiles/h2o.dir/lib/handler/configurator/file.c.o
    [ 64%] Building C object CMakeFiles/h2o.dir/lib/handler/configurator/headers.c.o
    [ 64%] Building C object CMakeFiles/h2o.dir/lib/handler/configurator/proxy.c.o
    [ 67%] Building C object CMakeFiles/h2o.dir/lib/handler/configurator/redirect.c.o
    [ 71%] Building C object CMakeFiles/h2o.dir/lib/handler/configurator/reproxy.c.o
    [ 71%] Building C object CMakeFiles/h2o.dir/lib/http1.c.o
    [ 75%] Building C object CMakeFiles/h2o.dir/lib/http2/connection.c.o
    [ 75%] Building C object CMakeFiles/h2o.dir/lib/http2/frame.c.o
    [ 78%] Building C object CMakeFiles/h2o.dir/lib/http2/hpack.c.o
    [ 78%] Building C object CMakeFiles/h2o.dir/lib/http2/scheduler.c.o
    [ 82%] Building C object CMakeFiles/h2o.dir/lib/http2/stream.c.o
    [ 82%] Building C object CMakeFiles/h2o.dir/deps/yaml/src/api.c.o
    [ 85%] Building C object CMakeFiles/h2o.dir/deps/yaml/src/dumper.c.o
    [ 85%] Building C object CMakeFiles/h2o.dir/deps/yaml/src/emitter.c.o
    [ 89%] Building C object CMakeFiles/h2o.dir/deps/yaml/src/loader.c.o
    [ 89%] Building C object CMakeFiles/h2o.dir/deps/yaml/src/parser.c.o
    [ 92%] Building C object CMakeFiles/h2o.dir/deps/yaml/src/reader.c.o
    [ 96%] Building C object CMakeFiles/h2o.dir/deps/yaml/src/scanner.c.o
    [ 96%] Building C object CMakeFiles/h2o.dir/deps/yaml/src/writer.c.o
    [100%] Building C object CMakeFiles/h2o.dir/src/main.c.o
    Linking C executable h2o
    [100%] Built target h2o

make install
    
    make install
    [  0%] Built target bundled-ssl
    [100%] Built target h2o
    Install the project...
    -- Install configuration: ""
    -- Installing: /usr/local/bin/h2o
    -- Up-to-date: /usr/local/share/h2o/fetch-ocsp-response

**Comment by centminmod** [comment] 2015-03-26 12:57
FYI going back to previous build of master/h2o alpha works find

**Comment by centminmod** [comment] 2015-03-26 13:50
FYI, tried on another CentOS server I have h2o running on and this with latest alpha pull of h2o works fine without segfaults. Would the h2o.conf itself possibly cause segfaults ? That is one of the differences  between the working h2o alpha and segfaulting h2o alpha

**Comment by centminmod** [comment] 2015-03-26 15:25
Ah I forgot, segfaulting CentOS h2o one is on CentOS 6.6 32bit OS while working one is on CentOS 6.6 64bit as such static OpenSSL 1.0.2a-chacha patched build was compiled differently so not sure if it's related

    if [[ "$(uname -m)" = 'x86_64' ]]; then
    	./config --prefix=${STATICLIBSSL} --openssldir=${STATICLIBSSL}/ssl enable-threads zlib no-shared experimental-jpake enable-md2 enable-rc5 enable-rfc3779 enable-gost enable-static-engine enable-ec_nistp_64_gcc_128
	else
		./config --prefix=${STATICLIBSSL} --openssldir=${STATICLIBSSL}/ssl enable-threads zlib no-shared
	fi

**Comment by centminmod** [comment] 2015-03-26 15:41
Okay found the culprit, if i remove the head.add entries from segfaulting h2o.conf it starts up find. My working h2o config didn't have the header.add entries

    header.add: "Link: </style.css>; rel=preload; as=stylesheet"
    header.add: "Link: </reset.css>; rel=preload; as=stylesheet"

HTH

**Comment by kazuho** [comment] 2015-03-26 21:28
@centminmod Tried on linux using a 32-bit build, but could not reproduce.

> Okay found the culprit, if i remove the head.add entries from segfaulting h2o.conf it starts up fine.

Can you reproduce the issue by adding the header to the configuration file in the 64-bit environment?

**Comment by centminmod** [comment] 2015-03-26 21:34
using both header.add on 64bit works fine without segfault so seems it's the 32bit that had problems

**Comment by centminmod** [comment] 2015-03-26 21:42
ok tried using just one header.add and 32bit works without segfaults, it's only when using 2x header.add

    header.set: "Link: </style.css>; rel=preload; as=stylesheet"
    #header.add: "Link: </reset.css>; rel=preload; as=stylesheet"

**Comment by centminmod** [comment] 2015-03-26 22:42
very weird stuff going on in 32bit h2o.conf

when i changed

    expires: 31 day

to

    expires: 900 second

i got segfault with 1x header.add and had to disable it again

**Comment by kazuho** [comment] 2015-03-30 04:43
@centminmod Would you mind providing me a minimal configuration file that causes the segfault?

**Comment by retsaot** [comment] 2015-03-30 12:47
@kazuho Version: https://github.com/h2o/h2o/commit/e3905d51bc12788959367cfd129e322b6dde59ef Config: [h2o.conf](https://gist.github.com/retsaot/d69eb9d618aaecc5f97e)  Uname: FreeBSD 10.1 i386
Adding another header.set or commenting an existing one prevents it from crashing.

```
curl --insecure 'http://localhost:8080/'
<html><body><p>It works!</p></body></html>
```
```
curl --insecure 'https://localhost:8081/'
Assertion failed: (!"FIXME"), function rewrite_headers, file /tmp/h2o/lib/handler/headers.c, line 92.
Abort
```

**Comment by kazuho** [comment] 2015-03-30 13:40
@retsaot Thank you for the file!  Will try to reproduce.

**Comment by kazuho** [comment] 2015-03-31 04:40
@retsaot Thanks to the configuration file I was able to spot and fix the bug.

As described in the commit log, there was a heap overrun while parsing the configuration file if the number of `header.*` directives applicable to any path context become greater than 3 (in case of 32-bit system) or 7 (in case of 64-bit system).

@centminmod I am not sure if this was your case as well; would you mind checking if the issue has been resolved?

**Comment by centminmod** [comment] 2015-03-31 05:23
seems like segfaults gone but now get duplicate headers if i have same header.add in more than one host

my h2o.conf at https://gist.github.com/centminmod/63afbb999ef4d8f079bf/0a8ec7e6b0ad67b9eba8af432e6a12b46e4a0c7c

    curl -I https://h2ohttp2.centminmod.com:8083/flags.html
    HTTP/1.1 200 OK
    Date: Tue, 31 Mar 2015 05:20:58 GMT
    Server: h2o/1.1.2-alpha1
    Connection: keep-alive
    Content-Length: 63859
    content-type: text/html
    last-modified: Sun, 29 Mar 2015 15:43:59 GMT
    etag: "55181dbf-f973"
    vary: accept-encoding
    cache-control: max-age=900
    powered by: h2o on centminmod.com
    link: </style.css>; rel=preload; as=stylesheet
    link: </reset.css>; rel=preload; as=stylesheet
    ssl host: 8083
    link: </style.css>; rel=preload; as=stylesheet
    link: </reset.css>; rel=preload; as=stylesheet

**Comment by kazuho** [comment] 2015-03-31 05:58
@centminmod 
> seems like segfaults gone

Thank you for the confirmation.  Closing the issue.

> but now get duplicate headers if i have same header.add in more than one host

Path-level contexts inherit the `header.*` settings from global level and host level.  In your case, you have same definition at global level and path level which leads to repeated output.

**Closed by kazuho** 2015-03-31 05:58 UTC

**Comment by devlearner** [comment] 2015-03-31 07:29
That's interesting... I came across this thread, and happened to catch the following line in the conf:

https://gist.github.com/centminmod/63afbb999ef4d8f079bf/0a8ec7e6b0ad67b9eba8af432e6a12b46e4a0c7c (L21)
```
header.add: "Powered by: h2o on centminmod.com"
```
note the space in the header field-name `Powered by:`

[I actually thought it was a source of error (apparantly not :) )]
I actually digged thru the specs trying to find some light; it didn't seem to specificly forbid this, but as a convention we typically avoid spaces in field names, like `Content-Length`, `Transfer-Encoding`

I do note that some implementations treat this differently: headers with spaces in the middle of field-names seem removed by squid in responses;  rejected by (http-parser used in) nghttpx with a 400 Bad Request; h2o (picohttpparser) seems lenient about this thou ;)

so as a matter of convention I would recommend changing the line to:
```
header.add: "Powered-by: h2o on centminmod.com"
```
by replacing the space with a `-` hyphen (for better compatibility) ;)

Thanks

**Comment by centminmod** [comment] 2015-03-31 08:27
thanks @kazuho didn't know headers had inheritance :)

thanks @devlearner added the hyphen :)
