### ISSUE TITLE
ENHANCE_YOUR_CALM race condition?

### ISSUE THREAD

**Issue by tatsuhiro-t** [h2o/h2o#132] opened 2015-01-31 15:33 UTC
While I performed benchmark tests against h2o without flow control using h2load, I saw several errors.
Those errors are RST_STREAM with ENHANCE_YOUR_CALM from h2o.
Reading h2o code, h2o sends this error when peer exceeds max concurrent streams limit.
The benchmark environment is that we run h2o standalone server (not reverse proxy mode) and use `h2load -n2000000 -c500 -m100 -w30 -W30`, both on the same machine.
`-w30 -W30` sets large enough flow control window so that it effectively disables flow control.

I didn't check everything, but one possible scenario is race condition when h2o closes stream and frame data are received by peer.
It seems that h2o assembles several frames into write buffer and sends them at once (maybe I'm wrong  in this aspect) and after these data are flushed, all related streams are post-processed (h2o_http2_stream_proceed).  h2o_http2_stream_proceed function closes a stream if we see END_STREAM flag set.  This means that it is possible that data are received by peer before h2o executes h2o_http2_stream_proceed if network is really fast (e.g., lo).  If this happens, peer sees END_STREAM in received data and issues new request.  Meanwhile, h2o gets this new request and sees that peer exceeds the stream limit and issue RST_STREAM with ENHANCE_YOUR_CALM.

We hit the same bug in nghttp2 code before. I just notify you just in case.

**Comment by tatsuhiro-t** [comment] 2015-01-31 17:34
The benchmark test I had is https://gist.github.com/tatsuhiro-t/5f3b170414582ac58091#file-results-md

**Comment by kazuho** [comment] 2015-02-02 02:28
Thank you for reporting the issue.  I have so far been unable to reproduce the issue, but the scenario sounds likely that such problem exists.  Thank you so much for the analysis in detail.  I will look into fixing the issue.

BTW, the benchmark tests looks great!  Seems lie I need to tweak H2O :-)

**Comment by kazuho** [comment] 2015-02-02 07:40
@tatsuhiro-t 
I have merged the possible fix (the commit above) into master.  Would you mind checking if the issue has been resolved?  I am still unable to reproduce the problem.

**Comment by tatsuhiro-t** [comment] 2015-02-02 12:31
It seems the commits referenced above was not merged into master yet.
So I pulled kazuho/issues/132 branch and ran tests.
I've done several tests, and did not encounter this issue.
It seems that those commits fixed this issue.

**Comment by kazuho** [comment] 2015-02-02 19:28
Thank you for the confirmation.  Closing as fixed.
Actually b810b39 (which is a rework of b810b39) is in the master.

**Closed by kazuho** 2015-02-02 19:28 UTC
