### ISSUE TITLE
SSI - server side includes support?

### ISSUE THREAD

**Issue by jimboykin** [h2o/h2o#1499] opened 2017-11-15 04:35 UTC
Any plan to support SSI (server side includes), it will make easy for nginx/apache user to smoothly migrate.

Thanks

**Comment by csmk** [comment] 2017-11-15 04:41
Duplicate of https://github.com/h2o/h2o/issues/243. It would be better if you continue the discussion there.

**Comment by kazuho** [comment] 2017-11-16 07:49
Closing as a duplicate.

**Closed by kazuho** 2017-11-16 07:49 UTC
