### ISSUE TITLE
Adopt fast technique used by Actix & Drogon

### ISSUE THREAD

**Issue by jobs-git** [h2o/h2o#2085] opened 2019-07-18 17:53 UTC
Tech empower round 18 are out, there actix beating H2O by miles! Maybe its possible to adopt their technique discussed here https://github.com/TechEmpower/FrameworkBenchmarks/issues/4834

**Comment by volyrique** [comment] 2019-07-20 11:39
I am not a maintainer of this project, but I implemented some of the code that uses H2O in the TechEmpower benchmarks, so here are my two cents: This is not really the appropriate place to discuss this. Out of all the TechEmpower tests, only 3 are more or less relevant to this project - plaintext, JSON serialization, and cached queries. The bottleneck in the rest is the database communication, which is irrelevant here.

There are few implementations of the cached queries test, so we can ignore it for the time being, and the JSON serialization results are pretty much identical in the top 20 (there's some measurement noise, of course, which causes the marginal differences). That leaves the plaintext test, in which the results are indeed bad. The reason, as far as I can tell, is that at least one system call is necessary per HTTP/1 response, and reducing that will require very invasive changes to code (essentially architectural), and will probably increase the memory usage; at least I wasn't able to figure out a way to do it with the current implementation. However, the plaintext test makes very heavy use of HTTP/1 pipelining (it sends 16 requests together, and obviously the best approach is to send the 16 responses in one go), and my impression is that this use case is not really of interest to the project - @kazuho can confirm, of course.

**Comment by jobs-git** [comment] 2019-12-22 19:53
I think database communication is relevant, the fact that its the bottleneck means that what we were benchmarking is the database communication and not h2o.

But yes, I agree with you, plaintext and cache queries needs to improve in h2o.

**Comment by jobs-git** [comment] 2020-06-01 04:28
@volyrique maybe its possible to use libpq request batching similar to what is used by actix and drogon https://2ndquadrant.github.io/postgres/libpq-batch-mode.html

**Comment by volyrique** [comment] 2020-06-01 16:56
I have a policy of using stable versions of any software dependencies (including `libh2o` itself), especially for components that are actively developed. Note that you didn't link to the official `libpq` repository, but a fork of it, so other than the performance numbers, it's not clear if there are any quality issues with the code, i.e. if there are any bugs that will be easily discovered by a proper code review, if it covers all the use cases that the upstream considers, and so on. Another problem with not being upstream is that it is not clear if this is going to be the final API, so if/when it is merged eventually (and there has been some work in that direction), any code that uses it may need to be rewritten. In short, I don't see the point of using an unproven set of code changes just to get some impressive performance numbers. Keep in mind that one of the TechEmpower criteria is that all implementations are production-grade, and I doubt that there are that many production environments that favor performance at the expense of pretty much everything else. However, don't get me wrong - as soon as this lands in upstream `libpq`, I will start using it immediately.

`actix` is completely irrelevant to the discussion because it uses its own database driver (written in Rust), not `libpq`.

**Comment by jobs-git** [comment] 2020-06-02 01:43
That is on point and well explained. So that leaves all other to the server implementation while the plain text here, I hope they find it interesting to update.

**Comment by volyrique** [comment] 2022-12-10 19:46
Now my code uses database query pipelining, and while its performance still lags behind other frameworks, it is not far, and I have some performance tuning to do anyway (which I am in the process of), so the situation may change soon.

However, I have also updated the implementation of the cached queries test, and I have noticed a minor issue that is relevant to this project: As far as I can tell, `libh2o` does not expose an interface to disable including the `Connection: keep-alive` header in the response, which AFAIK is unnecessary in HTTP/1.1, since connections are persistent by default. This issue potentially increases the size of small responses significantly.

**Comment by jobs-git** [comment] 2023-11-14 10:50
@volyrique great work! now h2o is ranked 4th in fortune and single query performance @ 94%

https://www.techempower.com/benchmarks/#hw=ph&test=fortune&section=data-r22

I am just wondering, plaintext is still relatively slower?

**Comment by volyrique** [comment] 2023-11-15 23:14
I have already explained what the issue with the plaintext test is in the first reply to this issue - nothing has changed; the behaviour is pretty much by design, I believe.

**Comment by jobs-git** [comment] 2023-11-20 16:37
thanks for the great work, cloaing now as plaintext seems to be another issue

**Closed** 2023-11-20 16:37 UTC
