### ISSUE TITLE
Build failed with Ruby 3

### ISSUE THREAD

**Issue by Jxck** [h2o/h2o#2789] opened 2021-07-14 05:47 UTC
build succeed in same environment with ruby 2.7 but change to ruby 3 (3.0.1p64) failed.

it's too long logs so I'll put very end of error.

```
rake aborted!
wrong number of arguments (given 2, expected 1)
Rakefile:37:in `install_D'
make[2]: *** [CMakeFiles/mruby.dir/build.make:57: CMakeFiles/mruby] Error 1
make[1]: *** [CMakeFiles/Makefile2:513: CMakeFiles/mruby.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
  54.48s user 6.77s system 60% cpu 1:42.06 total
[  0%] Built target gitrev
(in /home/jxck/dotfiles/pkg/h2o/deps/mruby)
PKG-CONFIG onigmo
PKG-CONFIG oniguruma
rake aborted!
wrong number of arguments (given 2, expected 1)
Rakefile:37:in `install_D'
make[2]: *** [CMakeFiles/mruby.dir/build.make:57: CMakeFiles/mruby] Error 1
make[1]: *** [CMakeFiles/Makefile2:513: CMakeFiles/mruby.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

Env
- Ubuntu 20.04 focal x64
- kernel: 5.4.0-74-generic
- ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]
- build target: current master [e44b7bd](https://github.com/h2o/h2o/commit/e44b7bd442d9e6cfbc38686bbf5286f99de004c6)

**Comment by syohex** [comment] 2021-07-14 07:21
It looks Ruby 3.0 keyword arguments specification(https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/).  Since Ruby 3.0, hash object is no longer converted into keyword arguments. So `Rakefile` should be fixed as below for Ruby 3.0(or removing verbose option). BTW mruby has already fixed this issue at https://github.com/mruby/mruby/commit/26e6e75ba6a59bc77c80a6ce5d207626cfed91a6. So this issue is fixed by updating mruby.

```diff
diff --git a/deps/mruby/Rakefile b/deps/mruby/Rakefile
index 6c160a5ed..b774122e4 100644
--- a/deps/mruby/Rakefile
+++ b/deps/mruby/Rakefile
@@ -33,10 +33,9 @@ load "#{MRUBY_ROOT}/tasks/benchmark.rake"
 load "#{MRUBY_ROOT}/tasks/gitlab.rake"
 
 def install_D(src, dst)
-  opts = { :verbose => $verbose }
-  FileUtils.rm_f dst, opts
-  FileUtils.mkdir_p File.dirname(dst), opts
-  FileUtils.cp src, dst, opts
+  FileUtils.rm_f dst, verbose: $verbose
+  FileUtils.mkdir_p File.dirname(dst), verbose: $verbose
+  FileUtils.cp src, dst, verbose: $verbose
 end
 
 ##############################
```

**Comment by kazuho** [comment] 2022-06-21 05:30
To be fixed by #3036.

**Comment by syohex** [comment] 2022-06-21 09:14
I have confirmed that the build is successful on `kazuho/mruby-3.1.0` branch with Ruby 3.0 on Ubuntu 22.04.  But its h2o does not work well. I suppose that `iij/mruby-require` does not work well with mruby 3.

Loading [mruby-require/mrblib/require.rb](https://github.com/h2o/h2o/blob/kazuho/mruby-3.1.0/deps/mruby-require/mrblib/require.rb) is failed at initializing mruby. The following line raises exception. I suppose you can check this issue by running ` ./mruby/host/bin/mirb` after `make`. 

https://github.com/iij/mruby-require/blob/master/mrblib/require.rb#L5

The exception is as below

```
No target class or module (TypeError)
```

This exception happens since mruby's this commit(https://github.com/mruby/mruby/commit/58e94427377952b0953bcdf2d544c62b0fefd4a6)

This `eval` line is not necessary because bundled mruby-eval supports variadic arguments(https://github.com/h2o/h2o/blob/kazuho/mruby-3.1.0/deps/mruby/mrbgems/mruby-eval/src/eval.c#L164). (While very old `mruby-eval` takes only one argument.). So I commented out that line and rebuild, retry, but I had another error as below.

```
fatal:/src/h2o/lib/handler/mruby.c:116:an error occurred while loading /usr/local/share/h2o/mruby/preloads.rb: undefined method 'const_missing' (NoMethodError)
```

I'm not sure why this happened yet. I'll check this later.

**Comment by syohex** [comment] 2022-06-29 05:21
- https://github.com/h2o/h2o/pull/3036/commits/d522f6cc322367a229242528a93d89a0e61bc22e
- https://github.com/h2o/h2o/pull/3036/commits/573649e85fadb2da297dfdd4e0bda11241a00575

I confirmed that it seems `iij/mruby-require` works well by above commits.

**Closed** 2022-07-12 06:08 UTC
