### ISSUE TITLE
Data corruption

### ISSUE THREAD

**Issue by 19h** [h2o/h2o#2135] opened 2019-09-30 12:02 UTC
Hey,

after testing upgrading to the latest H2O trunk I'm seeing a serious corruption issue on one of my servers.

It seems to be a forward-propagated error that corrupts everything after a certain character sequence in a file.

Respective source code: https://gist.githubusercontent.com/19h/7f91a900a7a0eba4577ac94f8c788526/raw/f3a42affa3592f7b707a1c9bb76911b358e53740/hero.html

The site itself: https://r2.darknet.dev

Corresponding h2o.conf: https://gist.githubusercontent.com/19h/7f91a900a7a0eba4577ac94f8c788526/raw/d8fccea8c0ae5e1c0c363c2a2082e0c50001655b/h2o.conf

Note how the corruption starts in the middle of the document:

![Firefox Nightly 2019-09-30 at 13 53 09@2x](https://user-images.githubusercontent.com/280212/65876940-cb75d580-e38a-11e9-9b38-8cd0fd28b925.png)

Regards

**Comment by kazuho** [comment] 2019-09-30 12:27
Thank you for reporting the issue. This is concerning.

Am I correct in assuming that the corruption was introduced at commit 93af1383b? I'd appreciate it if you could check that the issue can be reprocduced in 93af1383b but not in 90e1b9b88.

Having the understanding of between which commits we broke helps a lot.

**Comment by kazuho** [comment] 2019-10-01 08:24
Even though we fixed #2138, it is likely that the issue being fixed is unrelated to this issue. I have so far been impossible to reproduce or identify the cause.

**Comment by 19h** [comment] 2019-10-01 13:49
Hey @kazuho, I can confirm that the issue was introduced with 93af138.

**Comment by 19h** [comment] 2019-10-01 13:52
I oscillated between multiple different configurations and figured the issue is triggered by a top-level `gzip: ON`. H2o with gzip disabled does not trigger this regression.

**Comment by kazuho** [comment] 2019-10-01 14:31
Oh thanks for nailing down the cause. I hadn't considered `gzip: ON`. I'll try to reproduce the issue tomorrow.

**Comment by kazuho** [comment] 2019-10-02 01:34
@19h I think that the issue have been fixed with #2141 being merged. Would you mind giving a try?

**Comment by 19h** [comment] 2019-10-02 09:57
@kazuho I verified that your fix has solved this issue. Thanks for your effort!

**Closed** 2019-10-02 10:21 UTC
