### ISSUE TITLE
h2o/2.2.3 websocket error

### ISSUE THREAD

**Issue by Jxck** [h2o/h2o#1481] opened 2017-10-26 08:07 UTC
h2o/2.2.3 sends duplicate `Upgrade: websocket` Header in Response.
cause error in `new WebSocket()` on chrome.
h2o/2.2.2 works fine.

![h2o-ws-error](https://user-images.githubusercontent.com/322289/32041686-fa7bac2e-ba6f-11e7-9b2f-abdc5228daab.png)

**Comment by csmk** [comment] 2017-10-26 08:31
It has been fixed. Duplicate of https://github.com/h2o/h2o/issues/1467

**Comment by dch** [comment] 2017-11-09 23:49
thanks @csmk and @jxck for your report & follow-up!

**Closed by dch** 2017-11-09 23:49 UTC
