### ISSUE TITLE
placement for specific options for default server SSL in h2o.conf

### ISSUE THREAD

**Issue by centminmod** [h2o/h2o#238] opened 2015-03-18 03:21 UTC
Still a bit confusing for yaml format for h2o.conf as to where to place specific settings.

Using my h2o.conf as example at https://gist.github.com/centminmod/db18853abfd5aaf12617

    listen:
      host: 0.0.0.0
      port: 8081
      ssl:
    #    certificate-file: /usr/local/h2o/server.crt
    #    key-file: /usr/local/h2o/server.key
        certificate-file: /usr/local/h2o/centminmod.com-unified.crt
        key-file: /usr/local/h2o/centminmod.com.key
        minimum-version: TLSv1
        cipher-suite: ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA:!CAMELLIA    

where would I set the following settings

    expires: 1 day
    file.dirlisting: off
    file.send-gzip: on

tried a few different placements and do not see the expires header anywhere in `curl -I` checks ?

probably one reason why I sugegsted a full h2o.conf example https://github.com/h2o/h2o/issues/232 :)

**Comment by kazuho** [comment] 2015-03-18 04:01
Many of the directives can be used at various levels.

The marks `[ghp]` on [the list of each directives](https://gist.github.com/kazuho/f15b79211ea76f1bf6e5) indicate at which level the directives can be used.

`expires`, `file.dirlisting`, `file.send-gzip` are all marked as `[ghp]` which mean that they can be either used at the global level, for each host-specific context, or for each path specific context.

In case of `listen`, since it is marked as `[gh]`, it can be used either at the global level or at the host-specific context.

**Comment by centminmod** [comment] 2015-03-18 05:20
I tried it at global level - see h2o.conf at https://gist.github.com/centminmod/db18853abfd5aaf12617/169408041c60ced50791ce39ee1ec1ca4094bd59#file-h2o-conf-L15-L17 but not getting at expires headers set when i check against `https://localhost:8081` ?

**Comment by kazuho** [comment] 2015-03-18 06:36
@centminmod Cannot reproduce.  When adding `expires: 1 day` at the global level to the configuration file I created for #229 (which is essentially the same as yours), I see `cache-control: max-age=86400` appended to the headers.

Maybe you are looking for `expires`?  The directive adds `cache-control` header instead as described in the help.

**Comment by centminmod** [comment] 2015-03-18 06:42
haha indeed was looking for expires header - i see the cache-control header ! so all is good :)

    cache-control:max-age=86400
    content-type:text/html
    date:Wed, 18 Mar 2015 06:35:26 GMT
    etag:"550488d0-ed9"
    last-modified:Sat, 14 Mar 2015 19:15:28 GMT
    server:h2o/1.1.1
    status:200
    vary:accept-encoding

**Comment by kazuho** [comment] 2015-03-18 07:56
:+1:

**Closed by kazuho** 2015-03-18 07:56 UTC
