### ISSUE TITLE
No error status code received while stress testing h2o

### ISSUE THREAD

**Issue by s0j0urn** [h2o/h2o#726] opened 2016-01-26 20:39 UTC
Hello,

I am trying to stress test h2o using h2load.  Whenever a large number of requests fails h2load doesn't report any error status codes. I suppose it is not getting the response code from h2o

     h2load -n200000 -c1 -m100 -i ~/h2o-1.5.0-beta2/SCRIPTS/all_urls.txt

    starting benchmark...
    spawning thread #0: 1 total client(s). 200000 total requests
    TLS Protocol: TLSv1.2
    Cipher: ECDHE-RSA-AES128-GCM-SHA256
    Server Temp Key: ECDH P-256 256 bits
    Application protocol: h2
    progress: 10% done
    
    finished in 4.65s, 5956.86 req/s, 30.54MB/s
    requests: 200000 total, 27826 started, 200000 done, 27726 succeeded, 172274 failed, 172274 errored, 0 timeout
    status codes: 27726 2xx, 0 3xx, 0 4xx, 0 5xx
    traffic: 149060220 bytes total, 1443027 bytes headers (space savings 71.53%), 147058038 bytes data
                         min         max         mean         sd        +/- sd
    time for request:     3.92ms    106.90ms     14.17ms     10.23ms    86.44%
    time for connect:     5.10ms      5.10ms      5.10ms         0us   100.00%
    time to 1st byte:    14.04ms     14.04ms     14.04ms         0us   100.00%
    req/s           :    5958.32     5958.32     5958.32        0.00   100.00%

As You can see a lot many requests have failed but no error status code has been reported. Also, I'd like to ask is it fine that a bigger bunch of requests are getting failed?

**Comment by kazuho** [comment] 2016-01-27 05:24
Thank you for reporting the issue.

Looks like that the connection was terminated during the benchmark.

Q1. Do you see any message being emitted to the error log of H2O (or to stderr)?

Q2. I cannot reproduce the issue (when the backend is the file handler).  Can you please either: a) provide the h2o configuration file and all_urls.txt, or b) determine what handler (e.g. mruby, file, fastcgi, proxy, etc.) is causing the issue from the URL list used (or by changing the list)?

**Comment by s0j0urn** [comment] 2016-01-27 06:26
Thank you @kazuho for taking note of the issue I am facing.

I do not think I got any useful error log in this case:

    starting new worker 32339
    [INFO] raised RLIMIT_NOFILE to 4096
    h2o server (pid:32339) is ready to serve requests
    fetch-ocsp-response (using OpenSSL 1.0.2d 9 Jul 2015)
    failed to extract ocsp URI from examples/h2o/server.crt
    [OCSP Stapling] disabled for certificate file:examples/h2o/server.crt	

Here is the config file:

    # to find out the configuration commands, run: h2o --help
    user: pc_name
    hosts:
      "127.0.0.1.xip.io:8081":
        listen: 
          host: 127.0.0.1
          port: 8080
        paths:
            "/":
              file.dir: examples/doc_root
      "127.0.0.1.xip.io:8081":
        listen:
          host: 127.0.0.1
          port: 8081
          ssl:
            certificate-file: examples/h2o/server.crt
            key-file: examples/h2o/server.key
        paths:
          "/":
            mruby.handler: |
              Proc.new do |env|
               push_paths = []
               if env["PATH_INFO"].end_with?("html") || env["PATH_INFO"].eql?("/")
                 push_paths << "/pushed_resources/index.css"
               end
                [399, push_paths.empty? ? {} : {"link" => push_paths.map{|p| "<#{p}>; rel=preload"}.join("\n")}, []]
              end
            file.dir: examples/doc_root
    # https://h2o.examp1e.net/configure/access_log_directives.html#access-log
    # https://github.com/h2o/h2o/pull/493
    access-log:
        path: /home/pc_name/h2o_software/h2o-1.5.0-beta2/h20_access_log.txt
        format: "%h %l %u %t \"%r\" %s %b %{x-http2-push}o"
    error-log: /home/pc_name/h2o_software/h2o-1.5.0-beta2/h20_error_log.txt
    pid-file: /home/pc_name/h2o_software/h2o-1.5.0-beta2/h20_pid_file.pid

The file all_urls.txt just contains the URLs to 1 html + 1 css + 1 JSON + 4 JS + 193 images = 200 files.

**Comment by kazuho** [comment] 2016-01-27 07:42
Thank you for the information.  I will find time to reproduce the issue.

Meanwhile it would be great if you could clarify:

1. which version of H2O you are using (can be emitted by running `h2o -v`)
2. if removing the mruby handler (or the push) eliminate the issue

**Comment by s0j0urn** [comment] 2016-01-27 18:31
The version is 1.5.0-beta 2

    $h2o --version
    h2o version 1.5.0-beta2
    OpenSSL: OpenSSL 1.0.2d 9 Jul 2015
    mruby: YES

I removed the mruby handler and yes it did eliminate the issue. 
But I do need push to work in my test cases. I enabled push for h2load based on tatsuhiro-t advice here [#481](https://github.com/tatsuhiro-t/nghttp2/issues/481#issuecomment-172777740)

**Comment by kazuho** [comment] 2016-01-28 02:55
Thank you for the response.

> I enabled push for h2load based on tatsuhiro-t advice here #481

Thank you for the link.  Obviously I need to apply that change to h2load to reproduce the issue.

FWIW, a issue related to h2load was fixed in 1.6.0, and you may want to update https://github.com/h2o/h2o/pull/608, therefore upgrading to the newest version of 1.6 series might fix the issue.

**Comment by s0j0urn** [comment] 2016-01-28 04:14
Hi

I updated to version 1.6.3

    $h2o --version
    h2o version 1.6.3
	OpenSSL: OpenSSL 1.0.2d 9 Jul 2015
	mruby: YES

Unfortunately, the issue stands

    $ h2load -v -n200000 -c1 -m100 -i /home/intel/h2o_software/h2o-1.6.3/SCRIPTS/all_urls.txt 
    starting benchmark...
    spawning thread #0: 1 total client(s). 200000 total requests
    TLS Protocol: TLSv1.2
    Cipher: ECDHE-RSA-AES128-GCM-SHA256
    Server Temp Key: ECDH P-256 256 bits
    Application protocol: h2
    progress: 10% done
    
    finished in 2.63s, 10568.38 req/s, 54.17MB/s
    requests: 200000 total, 27846 started, 200000 done, 27746 succeeded, 172254 failed, 172254 errored, 0 timeout
    status codes: 27746 2xx, 0 3xx, 0 4xx, 0 5xx
    traffic: 149115210 bytes total, 1430919 bytes headers (space savings 70.83%), 147126421 bytes data
                         min         max         mean         sd        +/- sd
    time for request:     3.71ms     32.44ms      7.75ms      3.12ms    87.98%
    time for connect:     5.15ms      5.15ms      5.15ms         0us   100.00%
    time to 1st byte:     9.75ms      9.75ms      9.75ms         0us   100.00%
    req/s           :   10575.41    10575.41    10575.41        0.00   100.00%

Nothing useful in h2o error log and running `h2load` with `-v` didn't help or I am missing something.

**Comment by s0j0urn** [comment] 2016-01-29 04:59
I have observed this issue with HTTP/2 and not with HTTP/1.1.

**Comment by tatsuhiro-t** [comment] 2016-01-29 06:52
@s0j0urn  Can you share us the content of all_urls.txt?

**Comment by tatsuhiro-t** [comment] 2016-01-29 07:01
Right, I now reproduced this issue.
h2load has no debugging feature (yeah, I know it is desirable), so I tried nghttp using -m option to send multiple requests.  I got following log from it:
```
nghttp -nv https://localhost:3001/bug/something -m100
(snip)
[  0.055] recv (stream_id=123) :method: GET
[  0.055] recv (stream_id=123) :scheme: https
[  0.055] recv (stream_id=123) :authority: localhost:3001
[  0.055] recv (stream_id=123) :path: /sample.c
[  0.055] recv (stream_id=123) accept: */*
[  0.055] recv (stream_id=123) accept-encoding: gzip, deflate
[  0.055] recv (stream_id=123) user-agent: nghttp2/1.7.1-DEV
[  0.055] recv PUSH_PROMISE frame <length=11, flags=0x04, stream_id=123>
          ; END_HEADERS
          (padlen=0, promised_stream_id=110)
(snip)
[  0.055] [INVALID; error=Protocol error] recv PUSH_PROMISE frame <length=11, flags=0x04, stream_id=121>
          ; END_HEADERS
          (padlen=0, promised_stream_id=108)
```

It looks like h2o does not send promised stream ID in PUSH_PROMISE in increasing order.

**Comment by s0j0urn** [comment] 2016-01-29 07:02
@tatsuhiro-t

The file all_urls.txt just contains the URLs to 1 html + 1 css + 1 JSON + 4 JS + 193 images = 200 files. Together these 200 files constitute a page load of about 1.1 Mb. 

If the file all_urls.txt is still required I'll share it as soon as I have access to my laptop.

**Comment by tatsuhiro-t** [comment] 2016-01-29 07:03
@s0j0urn It looks like the issue does not depend on the all_urls.txt.  So no need to upload it.  Thank you.

**Comment by tatsuhiro-t** [comment] 2016-01-29 07:05
https://tools.ietf.org/html/rfc7540#section-5.1.1
>   The identifier of a newly established stream MUST be numerically
   greater than all streams that the initiating endpoint has opened or
   reserved.  This governs streams that are opened using a HEADERS frame
   and streams that are reserved using PUSH_PROMISE.  An endpoint that
   receives an unexpected stream identifier MUST respond with a
   connection error (Section 5.4.1) of type PROTOCOL_ERROR.

**Comment by kazuho** [comment] 2016-01-29 09:10
@tatsuhiro-t Thank you for looking into the cause of the bug.  I have now been able to spot the reason why push_promises gets sent in the wrong order (it occurs when number of in-flight streams (sum of push and pull) exceeds 100; the default value of [`http2-max-concurrent-requests-per-connection`](https://h2o.examp1e.net/configure/http2_directives.html#http2-max-concurrent-requests-per-connection)).

@s0j0urn Can you please retry with `http2-max-concurrent-requests-per-connection` set to 255?  I assume that would work as a workaround, under the assumption that you are also hitting the bug reported by @tatsuhiro-t.

Note: the document states that the default value of `http2-max-concurrent-requests-per-connection` is 256; this is incorrect.  The true default is 100.

**Comment by s0j0urn** [comment] 2016-01-29 18:20
@kazuho 

I added the directive to my configuration file at the global level but the error is still there.

Here is the config file with added directive

```
# to find out the configuration commands, run: h2o --help
user: pc_name
http2-max-concurrent-requests-per-connection: 255
hosts:
  "127.0.0.1.xip.io:8080":
    listen: 
      host: 127.0.0.1
      port: 8080
    paths:
        "/":
          file.dir: examples/doc_root
  "127.0.0.1.xip.io:8081":
    listen:
      host: 127.0.0.1
      port: 8081
      ssl:
        certificate-file: examples/h2o/server.crt
        key-file: examples/h2o/server.key
    paths:
      "/":
        mruby.handler: |
          Proc.new do |env|
           push_paths = []
           if env["PATH_INFO"].end_with?("html") || env["PATH_INFO"].eql?("/")
             push_paths << "/pushed_resources/index.css"
           end
            [399, push_paths.empty? ? {} : {"link" => push_paths.map{|p| "<#{p}>; rel=preload"}.join("\n")}, []]
          end
        file.dir: examples/doc_root
#        header.add: "Link: </css/index.css>; rel=preload; as=stylesheet"
# https://h2o.examp1e.net/configure/access_log_directives.html#access-log
# https://github.com/h2o/h2o/pull/493
access-log:
    path: /home/intel/h2o_software/h2o-1.6.3/h20_access_log.txt
    format: "%h %l %u %t \"%r\" %s %b %{x-http2-push}o"
error-log: /home/pc_name/h2o_software/h2o-1.6.3/h20_error_log.txt
pid-file: /home/pc_name/h2o_software/h2o-1.6.3/h20_pid_file.pid
```

I then used nghttp client to see the error I am getting.
` nghttp -nv https://localhost:8081/my-gallery/index.html -m1000`

The complete output: [Push Promise Stream ID error](https://gist.github.com/s0j0urn/1328ceae3d385839ad8c)

Note: I did not observe any error with -m set to 100

**Comment by kazuho** [comment] 2016-02-01 07:07
@s0j0urn I assume the issue has been fixed in #734.  Can you please check if the issue still persists _using h2load_?

@tatsuhiro-t Could it be the case that `nghttp -m nnn` sends the specified number of requests without respecting `SETTINGS_MAX_CONCURRENT_STREAMS` of the server?  When I run `nghttp -m 101` against H2O, I see the server respond with `RST_STREAM` even when the server pushes nothing.

**Comment by tatsuhiro-t** [comment] 2016-02-01 14:46
nghttp respects server's preference.  I think you are using older version of nghttp.  In the older version, nghttp may send 101 requests before reading server's SETTINGS.  That means when nghttp sends requests, it assumes server's MAX_CONCURRENT_STREAMS is unlimited.  When it sees server's SETTINGS, it updates max value accordingly.  To limit the initial inflight requests, use -M option.

This behaviour has changed in recent version of nghttp (and libnghttp2).  Now nghttp limits the initial inflight number of requests to 100 (which is sensible value).  If it gets server's SETTINGS, update it (increase or decrease).  Current -M option's default value reflects this, and is set to 100.

**Comment by s0j0urn** [comment] 2016-02-01 19:03
@kazuho 

Sorry the commit [#734](https://github.com/h2o/h2o/pull/734) did not fix the issue. 
I tried it by introducing the commit  to connection.c file locally and then rebuilding h2o as well as pulling the latest master branch and then building h2o.

With latest master branch, Here are the results :   

`$ h2o -version
h2o version 1.7.0-beta4
OpenSSL: OpenSSL 1.0.2d 9 Jul 2015
mruby: YES
`

nghttp command : `nghttp -nv https://localhost:8081/my-gallery/index.html -m200`

Terminal output : [ Stream error ](https://gist.github.com/s0j0urn/a43a14d4d52d734eba2b)

@tatsuhiro-t One thing I am not able to understand is that at the end of command output [ Stream error](https://gist.github.com/s0j0urn/a43a14d4d52d734eba2b) it says `Some requests were not processed. total=327, processed=189` however, I have requested the `index.html` 200 times and one css file is being pushed always i.e. 200+100 = 300. How the count is 327 ?

**Comment by kazuho** [comment] 2016-02-01 21:46
@tatsuhiro-t Thank you for the answer.
>  I think you are using older version of nghttp.

Yes. This was the case.  Upgrading to the newest version did the trick.

With my nghttp2 being updated I was able to reproduce @s0j0urn's issue.  There was an encoding bug in H2O that caused the issue when more than 127 push promises were sent over a single connection.  #737 fixes the problem.

**Comment by kazuho** [comment] 2016-02-01 23:55
@s0j0urn I have merged #737 to master.  Can you please check once more?

**Comment by s0j0urn** [comment] 2016-02-02 00:02
@kazuho Thank You

I am onto it. Will report back the test result in another 15 mins.

**Comment by s0j0urn** [comment] 2016-02-02 00:29
@kazuho Thanks a lot :)

The quick tests I have done for now...seems like [#737](https://github.com/h2o/h2o/pull/737) has resolved the issue.

Also, about my question to @tatsuhiro-t , is that extra 127 requests figure was coming from that encoding bug you mentioned.

**Comment by kazuho** [comment] 2016-02-02 00:40
@s0j0urn Glad to hear that the issue has been resolved.  Thank you for your help.

> Also, about my question to tatsuhiro-t , is that extra 127 requests figure was coming from that encoding bug you mentioned.

Yes.  In your test (`-m 200`), 200 requests were initiated by nghttp2, and H2O was pushing 200 requests.  So the expected number of requests to be processed was 400 (i.e. 200+200).

However, 128th PUSH_PROMISE frame (indicating a new push) was broken, causing nghttp2 to abort the connection.  Therefore, number of requests being observed ended up to be 327 (i.e. 200 + 127).

**Closed by kazuho** 2016-02-02 00:40 UTC

**Comment by s0j0urn** [comment] 2016-02-02 00:42
Thank you for the explanation :+1:
