### ISSUE TITLE
Server push precompressed files

### ISSUE THREAD

**Issue by proyb6** [h2o/h2o#1633] opened 2018-01-28 12:11 UTC
How do you push precompressed br and gz files which I found the CSS weren't push according to the Chrome's network graph, it works for images.
```
compress: [gzip, br]
file.send-compressed: on
http2-casper: on
...
mruby.handler: |
         Proc.new do |env|
           push_paths = []
           if /(\/|\.html)\z/.match(env["PATH_INFO"])
             push_paths << ["/tachyons.min.css", "style"]
             push_paths << ["img/logo.jpg", "jpeg"]
             push_paths << ["fonts/or.woff2", "woff2"]
           end
           [399, push_paths.empty? ? {} : {"link" => push_paths.map{|p| "<#{p[0]}>; rel=preload; as=#{p[1]}"}.join("\n")}, []]
         end
       file.dir: /var/h2o/www
```

**Comment by utrenkner** [comment] 2018-01-28 14:11
I have a very similar h2o.conf and here it works. I even checked the size to verify that the pushed stylesheets and javascripts are the precompressed ones and not compressed on-the-fly.

What happens in your setup? The CSS is not pushed? But the precompressed file is delivered upon the browser's request?

Just to be sure: Did you double check file name, path (you use the slash to indicate docroot for the CSS but relative paths for the image and font file)?

**Comment by proyb6** [comment] 2018-01-28 14:17
@utrenkner Yes, the CSS is not pushed, simply delivered as "br" as shown in the Google chrome's network Initiator column. How does your config looks like for precompressed CSS that has successfully pushed?

**Comment by proyb6** [comment] 2018-01-29 05:49
So is your his something that can be achieve to “push” precompressed be or gzipped static contents?

I have one such demo that is both gzip and push.
https://http2-push.appspot.com

**Comment by utrenkner** [comment] 2018-01-29 07:43
Again, your config looks pretty much the same as mine. There should be no issue with mixing push and pre-compressed files of any kind. h2o will deliver the pre-compressed file if configured to do so and if the browser signals that it can handle gz and/or br... it does not matter whether the request was initiated by the browser or via server push.

You say, you have a problem with the combination of server push and pre-compressed CSS. Did you test that the above example works with ``file.send-compressed: off``, i.e. the CSS is pushed in that case? And the other way around: Disabling server push but having ``file.send-compressed: on`` delivers the pre-compressed file? If not, the problem is definitely somewhere else.

Again, make sure the path is correct. And maybe check file permissions?

**Comment by proyb6** [comment] 2018-01-29 11:57
I have found the problem with minetype or extension!

```tachyons.min.css``` didn't get pushed but ```tachyons.css``` get pushed, it's a bug for a filename with 2 dots.

Ping @kazuho

**Comment by proyb6** [comment] 2018-01-29 12:18
Updated: After combination test, I found once I have off the http2-casper, the CSS (tachyons.min.css) get pushed. If I have turn on, it will deliver as anormal request from client side.

```
http2-casper: off
file.send-compressed: on
```

ping @kazuho is CASPER and Server Push can be enabled together?

**Comment by utrenkner** [comment] 2018-01-29 12:41
@proyb6 We see absolutely no problems with the combination of casper, server push and pre-compressed files. 

See this [webpagetest.org result from our homepage](https://www.webpagetest.org/result/180129_JF_ba57865f453415a86ff7a5433b436641/). All CSS and JS that comes from our own domain is pre-compressed and pushed. Casper is switched on, and thus in repeat-view non of theses CSS and JS files is served a second time.

From our h2o.conf, used with h2o's latest release (2.2.4)
```
http2-casper: ON 
http1-upgrade-to-http2: ON
file.send-compressed: ON
compress: ON 
[...]
        mruby.handler: |
          Proc.new do |env|
            push_paths = []
            if /^\/?$|\.(html)$/.match(env["PATH_INFO"])
              push_paths << "/typo3temp/javascript_a708894199.js?1295364422"
              push_paths << "/fileadmin/static/jquery-1.12.4.min.js"
              push_paths << "/fileadmin/static/solarserver_ohne_likes.js"
            end
            [399, push_paths.empty? ? {} : {"link" => push_paths.map{|p| "<#{p}>; rel=preload; as=script"}.join("\n")}, []]
          end
        mruby.handler: |
          Proc.new do |env|
            push_paths = []
            if /^\/$|\.(html)$/.match(env["PATH_INFO"])
              push_paths << "/typo3temp/stylesheet_4ca3260574.css?1498738035"
              push_paths << "/fileadmin/static/libraries.css"
              push_paths << "/fileadmin/static/template/template.css"
              push_paths << "/fileadmin/static/grid/grids.css"
              push_paths << "/fileadmin/static/module/mod.css"
              push_paths << "/fileadmin/static/content.css"
              push_paths << "/fileadmin/static/module/mod_skins.css"
              push_paths << "/fileadmin/static/eem_180125.css"
              push_paths << "/fileadmin/static/print.css"
            end
            [399, push_paths.empty? ? {} : {"link" => push_paths.map{|p| "<#{p}>; rel=preload; as=style"}.join("\n")}, []]
          end
```

**Comment by proyb6** [comment] 2018-01-29 13:02
I think Google Chrome 63.0.xxxx appear to be unstable, once time it's (Pushed/Index) and subsequent clear cache and hard reload become (Index). CSS sometime do push and sometime don't, it seems random.

**Comment by utrenkner** [comment] 2018-01-29 14:25
Strange, as long as the preload-link contained the ``as="style"``, I have never encountered an issue with any version of Chrome. Only when that information is missing, Chrome was sometimes re-requesting the resource because it couldn't match it properly.

**Comment by proyb6** [comment] 2018-01-29 17:08
I found changing to ```http2-idle-timeout: 1``` will solve the "push" issue, is it safe to set to 0?

**Comment by deweerdt** [comment] 2018-01-29 18:58
> I found changing to http2-idle-timeout: 1 will solve the "push" issue, is it safe to set to 1?

It is safe. This will cause connections to be closed faster, however. That can cause three issues that i can think of:
- This will prompt the client to re-open new connections to get new content, introducing extra latency
- Closing the connection means losing the HPACK context, making header compression less efficient
- Closing the connection means losing the push cache itself, since that's associated with the connection. https://jakearchibald.com/2017/h2-push-tougher-than-i-thought/

If you were able to reproduce your issue with webpage test, it might be easier to diagnose what's going on.

**Comment by proyb6** [comment] 2018-01-29 19:18
After setting to normal priority, the precompressed CSS file will push with CASPER enabled. 

```
# mime types, additional types and redefine of *.html
file.mime.settypes:
    "text/css":
         extensions: [".css"]
         is_compressible: yes
         priority: normal
```

**Closed** 2018-02-04 08:30 UTC
