### ISSUE TITLE
duplicate Date header on 2.3.0-beta1

### ISSUE THREAD

**Issue by Jxck** [h2o/h2o#1779] opened 2018-06-03 10:41 UTC
I update h2o on my blog to 2.3.0-beta1.

https://jxck.io/

and it responses duplicate Date header.
(in h2o/2.2.5 are fine)

![screen shot 2018-06-03 at 19 26 49](https://user-images.githubusercontent.com/322289/40885613-9e5a7108-6764-11e8-9534-08cb38e5a869.png)

my configs are on 

https://github.com/Jxck/jxck.io/blob/master/h2o.conf#L49-L121

**Comment by utrenkner** [comment] 2018-06-03 11:15
Duplicate of https://github.com/h2o/h2o/issues/1777

**Closed** 2018-06-04 02:51 UTC
