### ISSUE TITLE
ERR_CONNECTION_CLOSED on php files

### ISSUE THREAD

**Issue by chadouming** [h2o/h2o#445] opened 2015-08-17 02:07 UTC
For some reason, whenever i build using the master branch, i get the ERR_CONNECTION_CLOSED when trying to access php files. plain HTML works fine. I also found no error in the logs. The server works fine when using gzip on the fly branch. 

I am on latest Debian and use default build option from https://h2o.examp1e.net/install.html .

On a side note, I don't know if it's related, but even though i have mruby and libmruby-dev installed, cmake complain that it can't find it. Building seems to work fine anyway.

more details:

I've tried with more browser, and firefox was spitting a few warning like : 

Warning: session_start(): Cannot send session cookie - headers already sent  (output started at index.php:17) in index.php on line 20

line 17 is the <?php tag and line 20 is session_start();

code works fine on other server application.

**Comment by kazuho** [comment] 2015-08-17 02:38
@chadouming Are using `fastcgi.spawn` directive?  If that is the case, rebuilding H2O using the latest master branch might fix the problem; a bug related to the directive has just been fixed and merged to master (see #443).

> The server works fine when using gzip on the fly branch. 

Which of the following branches are you referring to?  #413 (last commit is 809f2de) or `kazuho/gzip-on-the-fly` branch (last commit is bb7de02)?  Clarifying between the two would help us bisect the issue.

> On a side note, I don't know if it's related, but even though i have mruby and libmruby-dev installed, cmake complain that it can't find it. Building seems to work fine anyway.

That is a non-issue.  Due to the various ways in how mruby is built we need to search for the library using two methods, and either method may report a _not-found_error (see the discussion on https://github.com/h2o/h2o/pull/378#issuecomment-116497726).

> I've tried with more browser, and firefox was spitting a few warning like :
> 
> Warning: session_start(): Cannot send session cookie - headers already sent (output started at index.php:17) in index.php on line 20
> 
> line 17 is the <?php tag and line 20 is session_start();
> 
> code works fine on other server application.

That sounds like an unrelated issue in your PHP application.  In case of Firefox, what error message are you seeing on the browser window?  Are you seeing this warning?

**Comment by chadouming** [comment] 2015-08-17 02:47
I tried with the fastcgi.spawn and fastcgi.connect. the latter is my current option and both did not work. I indeed use kazuho/gzip-on-the-fly and it work fine currently. The error i linked where from the firefox browser. It just works fine

**Comment by chadouming** [comment] 2015-08-17 03:31
Also, if that can be of any help, I am using https through tls (port 443). Havn't tried on not https, but html render just fine so i don't expect it to be the problem.

**Comment by kazuho** [comment] 2015-08-17 04:19
Thank you for the clarification.  I am so far been unable to reproduce the issue.

Two questions:

1. Can you try using non-HTTPS?  Use of HTTPS on Chrome / Firefox implies the use of HTTP2, while use of HTTP (non-TLS) means that HTTP/1.1 will be used.  I would like to know if the issue is specific to when using HTTP2 or not.

2. Are you using server push in your application (i.e. send `Link` header with `preload` attribute)?  The main difference between master and `kazuho/gzip-on-the-fly` branch is that the former has received modifications to the push logic (see #432), and that might have been the cause of the issue.

**Comment by chadouming** [comment] 2015-08-17 04:22
I indeed use link header, will try without those and i'll also try without
https tommorow.

**Comment by chadouming** [comment] 2015-08-17 04:46
Right call, not using https works. only removing the link header changed nothing though.

**Comment by kazuho** [comment] 2015-08-17 06:08
Hmm.  That means that, considering that Firefox is capable of accessing the website and that only PHP-generated contents trigger the error on Chrome, the issue exists in the HTTP2 implementation of either H2O or Chrome.

Can you send me the full HTTP response that is causing the error?  I.e. if you can give me the entire list HTTP headers being sent (the easiest way might be to copy them from the network panel of Firefox) as well as the HTML generated by PHP, I might be possible to reproduce the issue.

**Comment by chadouming** [comment] 2015-08-20 04:58
Good and bad news. I have was able to put the finger on the error. Everything go crazy when I add : 

http2-reprioritize-blocking-assets: ON

to the config file. Without it, it works just fine. The bad news is that I have no idea what it means. It was used in the example configuration so I thought it might be good to use it. One thing though, with this on, the server answered nothing to the browser. It's what caused the error. Another thing to note is that i was able to get the full page with this on using curl. I hope this is of any help. I am happy since I can use the master branch :D

**Comment by kazuho** [comment] 2015-08-20 07:03
@chadouming 
> Everything go crazy when I add: `http2-reprioritize-blocking-assets: ON`

Thank you for noticing that!  It really helps.

The option changes the order in which responses are sent (which is valid per HTTP/2 spec.) for certain web browsers including Chrome, but not Firefox (I am not sure if the option (when set to ON) changes the order of response sent to Curl).

So it is likely that it is either a bug in H2O or Chrome.  Can you send me the full page dump (including images, scripts, CSS, ...) obtained by Curl?  If you could, I will like to test if I can reproduce the issue using the files.

**Comment by HLFH** [comment] 2015-09-18 01:30
@kazuho Hi. I confirm the issue of @chadouming. And the workaround is to remove completely http2-reprioritize-blocking-assets: ON

I'm not using curl but with wget example.com on a WP setup, I got:

```<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr-FR" xml:lang="fr-FR">
<head>
        <meta name="viewport" content="width=device-width" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>WordPress &raquo; Installation</title>
        <link rel='stylesheet' id='buttons-css'  href='https://example.com/wp-includes/css/buttons.min.css?ver=4.3.1' type='text/css' media='all' />
<link rel='stylesheet' id='open-sans-css'  href='https://fonts.googleapis.com/css?family=Open+Sans%3A300italic%2C400italic%2C600italic%2C300%2C400%2C600&#038;subset=latin%2Clatin-ext&#038;ver=4.3.1' type='text/css' media='all' />
<link rel='stylesheet' id='install-css'  href='https://example.com/wp-admin/css/install.min.css?ver=4.3.1' type='text/css' media='all' />
<link rel='stylesheet' id='dashicons-css'  href='https://example.com/wp-includes/css/dashicons.min.css?ver=4.3.1' type='text/css' media='all' />
</head>
<body class="wp-core-ui">
<h1 id="logo"><a href="http://www.wordpress-fr.net/" tabindex="-1">WordPress</a></h1>

<h1>Bienvenue</h1>
<p>Bienvenue dans la très célèbre installation en 5 minutes de WordPress&nbsp;! Vous n&rsquo;avez qu&#8217;à remplir les informations demandées ci&#45;dessous et vous serez prêt à utiliser la plus extensible et puissante plateforme de publication de contenu au monde.</p>

<h1>Informations nécessaires</h1>
<p>Veuillez renseigner les informations suivantes. Ne vous inquiétez pas, vous pourrez les modifier plus tard.</p>

<form id="setup" method="post" action="install.php?step=2" novalidate="novalidate">
        <table class="form-table">
                <tr>
                        <th scope="row"><label for="weblog_title">Titre du site</label></th>
                        <td><input name="weblog_title" type="text" id="weblog_title" size="25" value="" /></td>
                </tr>
                <tr>
                        <th scope="row"><label for="user_login">Identifiant</label></th>
                        <td>
                        <input name="user_name" type="text" id="user_login" size="25" value="" />
                                <p>Les identifiants ne peuvent utiliser que des caractères alphanumériques, des espaces, des tirets bas ("_"), des traits d'union ("-"), des points et le symbole @.</p>
                                                </td>
                </tr>
                                <tr class="form-field form-required user-pass1-wrap">
                        <th scope="row">
                                <label for="pass1">
                                        Mot de passe                            </label>
                        </th>
                        <td>
                                <div class="">
                                                                                <input type="password" name="admin_password" id="pass1" class="regular-text" autocomplete="off" data-reveal="1" data-pw="#4GY6RYtwa3o2gUL7T" aria-describedby="pass-strength-result" />
                                        <button type="button" class="button button-secondary wp-hide-pw hide-if-no-js" data-start-masked="0" data-toggle="0" aria-label="Cacher le mot de passe">
                                                <span class="dashicons dashicons-hidden"></span>
                                                <span class="text">Cacher</span>
                                        </button>
                                        <div id="pass-strength-result" aria-live="polite"></div>
                                </div>
                                <p><span class="description important hide-if-no-js">
                                <strong>Important&nbsp;:</strong>
                                                                Vous aurez besoin de ce mot de passe pour vous connecter. Pensez à le stocker dans un lieu sûr.</span></p>
                        </td>
                </tr>
                <tr class="form-field form-required user-pass2-wrap hide-if-js">
                        <th scope="row">
                                <label for="pass2">Répétez le mot de passe                                      <span class="description">(obligatoire)</span>
                                </label>
                        </th>
                        <td>
                                <input name="admin_password2" type="password" id="pass2" autocomplete="off" />
                        </td>
                </tr>
                <tr class="pw-weak">
                        <th scope="row">Confirmation du mot de passe</th>
                        <td>
                                <label>
                                        <input type="checkbox" name="pw_weak" class="pw-checkbox" />
                                        Confirmer l&rsquo;utilisation d&rsquo;un mot de passe faible                            </label>
                        </td>
                </tr>
                                <tr>
                        <th scope="row"><label for="admin_email">Votre adresse de messagerie</label></th>
                        <td><input name="admin_email" type="email" id="admin_email" size="25" value="" />
                        <p>Vérifiez bien cette adresse de messagerie avant de continuer.</p></td>
                </tr>
                <tr>
                        <th scope="row">Vie privée</th>
                        <td colspan="2"><label><input type="checkbox" name="blog_public" id="blog_public" value="1"  checked='checked' /> Autoriser les moteurs de recherche à indexer ce site</label></td>
                </tr>
        </table>
        <p class="step"><input type="submit" name="Submit" id="submit" class="button button-large" value="Installer WordPress"  /></p>
        <input type="hidden" name="language" value="" />
</form>
<script type="text/javascript">var t = document.getElementById('weblog_title'); if (t){ t.focus(); }</script>
<script type='text/javascript' src='https://example.com/wp-includes/js/jquery/jquery.js?ver=1.11.3'></script>
<script type='text/javascript' src='https://example.com/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.2.1'></script>
<script type='text/javascript'>
/* <![CDATA[ */
var _zxcvbnSettings = {"src":"https:\/\/example.com\/wp-includes\/js\/zxcvbn.min.js"};
/* ]]> */
</script>
<script type='text/javascript' src='https://example.com/wp-includes/js/zxcvbn-async.min.js?ver=1.0'></script>
<script type='text/javascript'>
/* <![CDATA[ */
var pwsL10n = {"short":"Tr\u00e8s faible","bad":"Faible","good":"Moyenne","strong":"Forte","mismatch":"Non concordance"};
/* ]]> */
</script>
<script type='text/javascript' src='https://example.com/wp-admin/js/password-strength-meter.min.js?ver=4.3.1'></script>
<script type='text/javascript' src='https://example.com/wp-includes/js/underscore.min.js?ver=1.6.0'></script>
<script type='text/javascript'>
/* <![CDATA[ */
var _wpUtilSettings = {"ajax":{"url":"\/wp-admin\/admin-ajax.php"}};
/* ]]> */
</script>
<script type='text/javascript' src='https://example.com/wp-includes/js/wp-util.min.js?ver=4.3.1'></script>
<script type='text/javascript'>
/* <![CDATA[ */
var userProfileL10n = {"warn":"Votre nouveau mot de passe n\u2019a pas \u00e9t\u00e9 enregistr\u00e9.","show":"Afficher","hide":"Cacher","cancel":"Annuler","ariaShow":"Afficher le mot de passe","ariaHide":"Cacher le mot de passe"};
/* ]]> */
</script>
<script type='text/javascript' src='https://example.com/wp-admin/js/user-profile.min.js?ver=4.3.1'></script>
<script type='text/javascript' src='https://example.com/wp-admin/js/language-chooser.min.js?ver=4.3.1'></script>
<script type="text/javascript">
jQuery( function( $ ) {
        $( '.hide-if-no-js' ).removeClass( 'hide-if-no-js' );
} );
</script>
</body>
</html>
```

**Comment by kazuho** [comment] 2015-09-18 03:14
@HLFH Can you please retry with the latest HEAD?

An crashing bug when using `file.custom-handler` together with `http2-reprioritize-blocking-assets` has been found and fixed in #514.  I believe that the bug went into master on Aug. 11 as part of #436.

**Comment by HLFH** [comment] 2015-09-18 03:38
@kazuho Thanks for this PR! It would be simpler for me if you release H2O version 1.5.0-beta3 with https://github.com/h2o/h2o/pull/514 merge. Then I'll just have to flag [this package](https://aur.archlinux.org/packages/h2o/) out-of-date. And I'll update my h2o package on production and test it easily on my WP setup.

**Comment by kazuho** [comment] 2015-09-22 03:58
@HLFH OK. I've shipped 1.5.0-beta3.  Hope it helps. https://github.com/h2o/h2o/releases/tag/v1.5.0-beta3

**Comment by HLFH** [comment] 2015-09-22 07:08
@kazuho Thanks a lot! Adding http2-reprioritize-blocking-assets is now perfectly ok and there is no more conflict with php files. You can close this issue.

**Comment by kazuho** [comment] 2015-09-22 08:57
:+1:

**Closed by kazuho** 2015-09-22 08:57 UTC

**Comment by chadouming** [comment] 2015-09-23 00:30
I confirm that this fixed my problem.
